server:
  port: 8090
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost/Todo
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
